In [53]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [54]:
df=pd.read_excel("../SurveyDataset/SurveyForm.xlsx",error_bad_lines = False)

In [55]:
df.head()

,Which age group do you belong to?,Sex,What is your current family type?,How many hours do you sleep per day?,Who do you sleep with usually in the bedroom?,How is your quality of sleep?,Does your health limit you in doing daily physical activities? [Light activities],Does your health limit you in doing daily physical activities? [Moderate activities],Does your health limit you in doing daily physical activities? [Heavy activities],How often do you consume alcohol in a week?,...,You see yourself as Critical/ Quarrelsome,You see yourself as Dependable/ Self-disciplined,You see yourself as Anxious/ Easily upset,You see yourself as Open to new experiences/ Complex,You see yourself as Reserved/ Quiet,You see yourself as Sympathetic/ Warm,You see yourself as Disorganised/ Careless,You see yourself as Calm/ Emotionally stable,You see yourself as Conventional/ Uncreative,Unnamed: 49
0,18 - 25,Male,Joint,4-6,With parents,Very good,No problem,No problem,No problem,I don’t drink alcohol,...,3,6,1,6,7,7,3,7,2,NaN
1,18 - 25,Male,Nuclear,7-9,Alone,Good,Very much,Moderately,Very less,I don’t drink alcohol,...,3,3,5,5,7,5,2,2,7,NaN
2,18 - 25,Female,Nuclear,7-9,Brother,Good,Very much,Very much,Very much,I don’t drink alcohol,...,4,7,3,5,7,5,1,5,1,NaN
3,18 - 25,Female,Nuclear,<4,Alone,Average,No problem,No problem,No problem,I don’t drink alcohol,...,3,4,4,7,1,7,5,6,7,NaN
4,18 - 25,Male,Joint,7-9,With parents,Very good,Very less,Moderately,Very less,I don’t drink alcohol,...,4,5,3,7,2,6,1,3,2,NaN

In [56]:
r,c=df.shape

In [57]:
# dropping the last 2 columns
# unamed columns are not needed and can be dropped
# dropping the name column
df=df.iloc[:,:49]
df.head()

,Which age group do you belong to?,Sex,What is your current family type?,How many hours do you sleep per day?,Who do you sleep with usually in the bedroom?,How is your quality of sleep?,Does your health limit you in doing daily physical activities? [Light activities],Does your health limit you in doing daily physical activities? [Moderate activities],Does your health limit you in doing daily physical activities? [Heavy activities],How often do you consume alcohol in a week?,...,You see yourself as Extraverted/ Enthusiastic,You see yourself as Critical/ Quarrelsome,You see yourself as Dependable/ Self-disciplined,You see yourself as Anxious/ Easily upset,You see yourself as Open to new experiences/ Complex,You see yourself as Reserved/ Quiet,You see yourself as Sympathetic/ Warm,You see yourself as Disorganised/ Careless,You see yourself as Calm/ Emotionally stable,You see yourself as Conventional/ Uncreative
0,18 - 25,Male,Joint,4-6,With parents,Very good,No problem,No problem,No problem,I don’t drink alcohol,...,6,3,6,1,6,7,7,3,7,2
1,18 - 25,Male,Nuclear,7-9,Alone,Good,Very much,Moderately,Very less,I don’t drink alcohol,...,3,3,3,5,5,7,5,2,2,7
2,18 - 25,Female,Nuclear,7-9,Brother,Good,Very much,Very much,Very much,I don’t drink alcohol,...,5,4,7,3,5,7,5,1,5,1
3,18 - 25,Female,Nuclear,<4,Alone,Average,No problem,No problem,No problem,I don’t drink alcohol,...,6,3,4,4,7,1,7,5,6,7
4,18 - 25,Male,Joint,7-9,With parents,Very good,Very less,Moderately,Very less,I don’t drink alcohol,...,6,4,5,3,7,2,6,1,3,2

In [58]:
df['Sex'].unique()

array(['Male', 'Female', 'Prefer not to say'], dtype=object)

In [59]:
df['How often do you consume alcohol in a week?'].unique()

array(['I don’t drink alcohol', 'once a week', '2-3 time a week',
       'ocassionally', 'Rarely', '1-2 times a month', 'Occasionally ',
       'Rarely ', 'Once a month', 'Once in a couple of months ',
       'Occasionally', 'Everyday', '3-4 times a year ',
       'once every few months', 'Once in 2 weeks', '1-2 times in a year',
       'Once in a month or two',
       'only drink during parties (occasionally)', 'Very rarely',
       'Once in 2-3 weeks', 'Once a month ',
       "Rarely when an outing with friends. Can't say weekly its in between months",
       'Once in 2 months', 'Once or twice a month',
       'Once or twice a month. ', 'once a month or two',
       'Haven’t consumed in the last 4 months', 'Once in 30-40 days',
       'Twice a month '], dtype=object)

In [60]:
# I dont drink alcohol
# 3-5 times a week
# Once a week
# Once a month
# Occasionally

In [61]:
l1=['once a week','2-3 time a week','ocassionally','Rarely','1-2 times a month','Occasionally ','Rarely ',
    'Once in a couple of months ','Everyday','3-4 times a year ','once every few months', 
    'Once in 2 weeks', '1-2 times in a year','Once in a month or two','only drink during parties (occasionally)', 
    'Very rarely','Once in 2-3 weeks', 'Once a month ',"Rarely when an outing with friends. Can't say weekly its in between months",
       'Once in 2 months', 'Once or twice a month',
       'Once or twice a month. ', 'once a month or two',
       'Haven’t consumed in the last 4 months', 'Once in 30-40 days',
       'Twice a month ']

In [62]:
l2=['Once a week','3-5 times a week','Occasionally','Occasionally','Once a month','Occasionally','Occasionally',
    'Once a month','3-5 times a week','Occasionally','Occasionally',
    'Once a week','Occasionally','Occasionally','Occasionally',
    'Occasionally','Once a month','Once a month','Occasionally','Once a month',
    'Once a week','Once a week','Once a week',
    'Occasionally','Once a month','Once a month']

In [63]:
df['How often do you consume alcohol in a week?'].replace(l1,l2,inplace=True)

In [64]:
df['How often do you consume alcohol in a week?'].unique()

array(['I don’t drink alcohol', 'Once a week', '3-5 times a week',
       'Occasionally', 'Once a month'], dtype=object)

In [65]:
df['How often do you smoke in a day?'].unique()

array(['I don’t smoke', 'Rarely', '1 - 5 times a day',
       '6 - 15 times a day', 'Once or twice in a year ( very rare )',
       'once in a week or 15 days '], dtype=object)

In [66]:
# I don't smoke
# 1-5 times a day
# 6-15 times a day
# Occasionally

In [67]:
l1=['once in a week or 15 days ','Once or twice in a year ( very rare )','Rarely']

In [68]:
l2=['Occasionally','Occasionally','Occasionally']

In [69]:
df['How often do you smoke in a day?'].replace(l1,l2,inplace=True)

In [70]:
df['How often do you smoke in a day?'].unique()

array(['I don’t smoke', 'Occasionally', '1 - 5 times a day',
       '6 - 15 times a day'], dtype=object)

In [71]:
df['Who do you sleep with usually in the bedroom?'].unique()

array(['With parents', 'Alone', 'Brother', 'Sister ', 'With sisters',
       'With children', 'Sister', 'Younger brother ', 'With roommates',
       'With partner', 'sibling', 'With my other pillow', 'Sibling',
       'With pet', 'With sibling', 'sibling and pets', 'Sibling ',
       'Siblings ', 'Brother ', 'Siblings', 'With sister'], dtype=object)

In [72]:
# Alone
# With Parents
# With Siblings
# With Children
# With Roommates
# With Partner

In [73]:
l1=['Brother', 'Sister ', 'With sisters','Sister', 'Younger brother ','sibling', 
    'With my other pillow', 'Sibling',
       'With pet', 'With sibling', 'sibling and pets', 'Sibling ',
       'Siblings ', 'Brother ', 'Siblings', 'With sister']

In [74]:
l2=['With Siblings','With Siblings','With Siblings','With Siblings','With Siblings','With Siblings','Alone','With Siblings','Alone',
    'With Siblings','With Siblings','With Siblings','With Siblings','With Siblings','With Siblings','With Siblings']

In [75]:
df['Who do you sleep with usually in the bedroom?'].replace(l1,l2,inplace=True)

In [76]:
df['Who do you sleep with usually in the bedroom?'].unique()

array(['With parents', 'Alone', 'With Siblings', 'With children',
       'With roommates', 'With partner'], dtype=object)

In [77]:
df['Who would you go to if you were having mental health issues?'].unique()

array(['Therapist/Psychiatrist/Psychologist', 'Friends',
       'Family/Relatives', 'Family doctor', 'Fam & Friends are equal',
       'Courses like happy thought/ art of leaving I had taken treatment doing these courses . Now wish to do Vipasanna ',
       'Friends for minor issues', 'Maybe / I will keep to myself',
       'You can go to everyone above. Not sure!!', 'I need a shift',
       'no one'], dtype=object)

In [78]:
# Therapist/Psychiatrist/Psychologist
# Friends
# Family/Relatives
# Family doctor
# No one

In [79]:
l1=['Fam & Friends are equal',
       'Courses like happy thought/ art of leaving I had taken treatment doing these courses . Now wish to do Vipasanna ',
       'Friends for minor issues', 'Maybe / I will keep to myself',
       'You can go to everyone above. Not sure!!', 'I need a shift',
       'no one']

In [80]:
l2=['Family/Relatives','Therapist/Psychiatrist/Psychologist','Friends','No one','Family/Relatives','No one','No one']

In [81]:
df['Who would you go to if you were having mental health issues?'].replace(l1,l2,inplace=True)

In [82]:
df['Who would you go to if you were having mental health issues?'].unique()

array(['Therapist/Psychiatrist/Psychologist', 'Friends',
       'Family/Relatives', 'Family doctor', 'No one'], dtype=object)

In [83]:
cols=['Fear and shame','Limited awareness','Lack of Knowledge','Feelings of inadequacy','Finance','Distrust','Hopelessness',
     'Unavailability','Practical barriers','Stigma']

In [84]:
data=np.zeros((r, 10),dtype=int)

In [85]:
df_add = pd.DataFrame(data=data,columns=cols)
df = pd.concat([df,df_add], axis=1)
df.head()

,Which age group do you belong to?,Sex,What is your current family type?,How many hours do you sleep per day?,Who do you sleep with usually in the bedroom?,How is your quality of sleep?,Does your health limit you in doing daily physical activities? [Light activities],Does your health limit you in doing daily physical activities? [Moderate activities],Does your health limit you in doing daily physical activities? [Heavy activities],How often do you consume alcohol in a week?,...,Fear and shame,Limited awareness,Lack of Knowledge,Feelings of inadequacy,Finance,Distrust,Hopelessness,Unavailability,Practical barriers,Stigma
0,18 - 25,Male,Joint,4-6,With parents,Very good,No problem,No problem,No problem,I don’t drink alcohol,...,0,0,0,0,0,0,0,0,0,0
1,18 - 25,Male,Nuclear,7-9,Alone,Good,Very much,Moderately,Very less,I don’t drink alcohol,...,0,0,0,0,0,0,0,0,0,0
2,18 - 25,Female,Nuclear,7-9,With Siblings,Good,Very much,Very much,Very much,I don’t drink alcohol,...,0,0,0,0,0,0,0,0,0,0
3,18 - 25,Female,Nuclear,<4,Alone,Average,No problem,No problem,No problem,I don’t drink alcohol,...,0,0,0,0,0,0,0,0,0,0
4,18 - 25,Male,Joint,7-9,With parents,Very good,Very less,Moderately,Very less,I don’t drink alcohol,...,0,0,0,0,0,0,0,0,0,0

In [86]:
old=list(df['What do you think is the reason for people not considering getting treated for mental health related problems?'])

In [87]:
ind=0
for i in old:
    val=i.split("/")
    for k in val:
        k=k.strip()
        for j in cols:
            if(k==j):
                df.loc[ind:ind,j]=1
                break
    ind=ind+1

In [88]:
df.head()

,Which age group do you belong to?,Sex,What is your current family type?,How many hours do you sleep per day?,Who do you sleep with usually in the bedroom?,How is your quality of sleep?,Does your health limit you in doing daily physical activities? [Light activities],Does your health limit you in doing daily physical activities? [Moderate activities],Does your health limit you in doing daily physical activities? [Heavy activities],How often do you consume alcohol in a week?,...,Fear and shame,Limited awareness,Lack of Knowledge,Feelings of inadequacy,Finance,Distrust,Hopelessness,Unavailability,Practical barriers,Stigma
0,18 - 25,Male,Joint,4-6,With parents,Very good,No problem,No problem,No problem,I don’t drink alcohol,...,1,0,1,1,0,0,1,0,0,0
1,18 - 25,Male,Nuclear,7-9,Alone,Good,Very much,Moderately,Very less,I don’t drink alcohol,...,1,0,1,0,1,1,1,0,1,0
2,18 - 25,Female,Nuclear,7-9,With Siblings,Good,Very much,Very much,Very much,I don’t drink alcohol,...,1,1,1,1,0,0,1,0,1,1
3,18 - 25,Female,Nuclear,<4,Alone,Average,No problem,No problem,No problem,I don’t drink alcohol,...,1,1,1,1,1,1,1,1,1,1
4,18 - 25,Male,Joint,7-9,With parents,Very good,Very less,Moderately,Very less,I don’t drink alcohol,...,1,1,1,1,1,1,1,1,1,1

In [89]:
from sklearn import preprocessing 
label_enc = preprocessing.LabelEncoder()
df["age class"]=label_enc.fit_transform(df["Which age group do you belong to?"])
list(label_enc.classes_)

['18 - 25', '25 - 35', '35 - 45', '45 - 60']

In [90]:
from sklearn import preprocessing 
label_enc = preprocessing.LabelEncoder()
df["Gender"]=label_enc.fit_transform(df["Sex"])
list(label_enc.classes_)

['Female', 'Male', 'Prefer not to say']

In [91]:
df.head()

,Which age group do you belong to?,Sex,What is your current family type?,How many hours do you sleep per day?,Who do you sleep with usually in the bedroom?,How is your quality of sleep?,Does your health limit you in doing daily physical activities? [Light activities],Does your health limit you in doing daily physical activities? [Moderate activities],Does your health limit you in doing daily physical activities? [Heavy activities],How often do you consume alcohol in a week?,...,Lack of Knowledge,Feelings of inadequacy,Finance,Distrust,Hopelessness,Unavailability,Practical barriers,Stigma,age class,Gender
0,18 - 25,Male,Joint,4-6,With parents,Very good,No problem,No problem,No problem,I don’t drink alcohol,...,1,1,0,0,1,0,0,0,0,1
1,18 - 25,Male,Nuclear,7-9,Alone,Good,Very much,Moderately,Very less,I don’t drink alcohol,...,1,0,1,1,1,0,1,0,0,1
2,18 - 25,Female,Nuclear,7-9,With Siblings,Good,Very much,Very much,Very much,I don’t drink alcohol,...,1,1,0,0,1,0,1,1,0,0
3,18 - 25,Female,Nuclear,<4,Alone,Average,No problem,No problem,No problem,I don’t drink alcohol,...,1,1,1,1,1,1,1,1,0,0
4,18 - 25,Male,Joint,7-9,With parents,Very good,Very less,Moderately,Very less,I don’t drink alcohol,...,1,1,1,1,1,1,1,1,0,1

In [92]:
# main questions
cols=list(df.iloc[:,18:39].columns)
cols

['Do you find it hard to calm down after something upset you?',
 'Were you aware of the dryness in your mouth?',
 'Were you not able to experience positive feelings?',
 'Do you experience breathing difficulty (eg: excessively rapid breathing/breathlessness in the absence of physical exertion)?',
 'Do you find it difficult to work up the initiative to do things?',
 'Do you tend to over-react in situations?',
 'Do you experience trembling (eg: in the hands)?',
 'Do you find yourself in a state of nervous tension?',
 'Are you worried about situations in which you might panic and make a fool of yourself?',
 'Do you feel that you have nothing to look forward to?',
 'Do you find yourself getting agitated?',
 'Do you find it difficult to relax?',
 'Do you feel sad and depressed?',
 'Do you find it difficult to tolerate interruptions while doing something?',
 'Do you find yourself on the verge of panicking?',
 'Do you find it hard to get enthusiastic about things?',
 "Do you feel you aren't worth much as a person?",
 'Do you find yourself getting impatient when you are delayed in any way (eg/ elevators/ traffic lights/ being kept waiting).',
 'How aware are you of the action of your heart in the absence of any physical exertion (eg: sense of heart rate increase/ heart missing a beat)?',
 'Do you feel scared without any good reason?',
 'Do you feel that life has become meaningless?']

In [93]:
dass=['S','A','D','A','D','S','A','S','A','D','S','S','D','S','A','D','D','S','A','A','D']
i=1
n=[]
for d,c in zip(dass,cols):
    old=c
    new='Q'+str(i)+"("+d+")"
    n.append(new)
    df.rename(columns={old:new}, inplace=True)
    i=i+1

for i in df.columns:
    if(i not in n):
        n.append(i)

In [94]:
df.iloc[:,18:39].head()

,Q1(S),Q2(A),Q3(D),Q4(A),Q5(D),Q6(S),Q7(A),Q8(S),Q9(A),Q10(D),...,Q12(S),Q13(D),Q14(S),Q15(A),Q16(D),Q17(D),Q18(S),Q19(A),Q20(A),Q21(D)
0,1,0,0,0,3,2,0,2,0,0,...,0,1,0,0,0,0,2,0,0,1
1,2,1,2,0,2,3,2,2,3,3,...,3,3,3,3,0,3,2,1,2,3
2,1,2,2,1,1,1,2,3,3,2,...,2,2,1,1,2,2,2,1,3,2
3,2,1,0,0,2,2,2,2,2,1,...,2,2,2,2,1,2,2,1,0,2
4,2,0,0,0,1,2,0,0,2,0,...,1,0,1,2,1,0,0,2,1,3

In [95]:
df_dep=pd.DataFrame()
df_str=pd.DataFrame()
df_anx=pd.DataFrame()
# main questions
cols=list(df.iloc[:,18:39].columns)

In [96]:
for i in cols:
    if(i.find("(D)")!=-1):
        df_dep[i]=df[i]
    if(i.find("(A)")!=-1):
        df_anx[i]=df[i]
    if(i.find("(S)")!=-1):
        df_str[i]=df[i]

In [97]:
cols=list(df.iloc[:,39:49].head().columns)

In [98]:
i=1
n=[]
for c in cols:
    old=c
    new='TIPI'+str(i)
    n.append(new)
    df.rename(columns={old:new}, inplace=True)
    i=i+1

In [99]:
df.iloc[:,39:49].head()

   TIPI1  TIPI2  TIPI3  TIPI4  TIPI5  TIPI6  TIPI7  TIPI8  TIPI9  TIPI10
0      6      3      6      1      6      7      7      3      7       2
1      3      3      3      5      5      7      5      2      2       7
2      5      4      7      3      5      7      5      1      5       1
3      6      3      4      4      7      1      7      5      6       7
4      6      4      5      3      7      2      6      1      3       2

In [100]:
df.head()

,Which age group do you belong to?,Sex,What is your current family type?,How many hours do you sleep per day?,Who do you sleep with usually in the bedroom?,How is your quality of sleep?,Does your health limit you in doing daily physical activities? [Light activities],Does your health limit you in doing daily physical activities? [Moderate activities],Does your health limit you in doing daily physical activities? [Heavy activities],How often do you consume alcohol in a week?,...,Lack of Knowledge,Feelings of inadequacy,Finance,Distrust,Hopelessness,Unavailability,Practical barriers,Stigma,age class,Gender
0,18 - 25,Male,Joint,4-6,With parents,Very good,No problem,No problem,No problem,I don’t drink alcohol,...,1,1,0,0,1,0,0,0,0,1
1,18 - 25,Male,Nuclear,7-9,Alone,Good,Very much,Moderately,Very less,I don’t drink alcohol,...,1,0,1,1,1,0,1,0,0,1
2,18 - 25,Female,Nuclear,7-9,With Siblings,Good,Very much,Very much,Very much,I don’t drink alcohol,...,1,1,0,0,1,0,1,1,0,0
3,18 - 25,Female,Nuclear,<4,Alone,Average,No problem,No problem,No problem,I don’t drink alcohol,...,1,1,1,1,1,1,1,1,0,0
4,18 - 25,Male,Joint,7-9,With parents,Very good,Very less,Moderately,Very less,I don’t drink alcohol,...,1,1,1,1,1,1,1,1,0,1

In [101]:
df_dep.head()

   Q3(D)  Q5(D)  Q10(D)  Q13(D)  Q16(D)  Q17(D)  Q21(D)
0      0      3       0       1       0       0       1
1      2      2       3       3       0       3       3
2      2      1       2       2       2       2       2
3      0      2       1       2       1       2       2
4      0      1       0       0       1       0       3

In [102]:
#  saving the dataframe
df_dep.to_csv('../SurveyDataset/Depression.csv',index=False)
df_anx.to_csv('../SurveyDataset/Anxiety.csv',index=False)
df_str.to_csv('../SurveyDataset/Stress.csv',index=False)

In [103]:
#  saving the preprocessed dataframe
df.to_csv('../SurveyDataset/CleanData.csv',index=False)

In [104]:
df_dep.head()

   Q3(D)  Q5(D)  Q10(D)  Q13(D)  Q16(D)  Q17(D)  Q21(D)
0      0      3       0       1       0       0       1
1      2      2       3       3       0       3       3
2      2      1       2       2       2       2       2
3      0      2       1       2       1       2       2
4      0      1       0       0       1       0       3